import { Inter } from "next/font/google"
import { Header } from "@/components/Header"
import { TopBar } from "@/components/TopBar"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-1 lg:grid-cols-12">
          <div className="col-span-1">
            <Header />
          </div>
          <div className="relative min-h-screen overflow-hidden bg-gray-50 col-span-11">
            <TopBar />
            <div className="absolute inset-0 bg-[url(/img/grid.svg)] bg-center"></div>
            <div className="relative">
              <div className="divide-y divide-gray-300/50">
                <div className="leading-7 lg:px-5 lg:py-3">{children}</div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
